language: node_js
node_js: "lts/*"
cache: yarn
install: yarn
script:
  - yarn test
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
  skip_cleanup: true
# notifications:
#   webhooks:
#     on_start: always
#     urls:
#       - secure: "<Encrypted Url here>"
