/* eslint-env node */
// NOTE: This file is run pre build and creates `app.components.js`.
const { createComponentsFile } = require('@creuna/codegen');
const path = require('path');

const eslintConfig = require('../.eslintrc.json');

const disclaimers = [
  '// NOTE: Do not edit this file. It is built by running `./scripts/create-app-components.js`',
  '// NOTE: The imported/exported components are exposed to the global scope'
].join('\n');

createComponentsFile({
  componentsPath: path.join(__dirname, '..', 'source', 'components'),
  fileHeader: disclaimers,
  fileName: 'app.components.js',
  outputPath: path.resolve(__dirname, '..', 'source'),
  prettierOptions: eslintConfig.rules['prettier/prettier'][1]
});
